export const siteConfig = {
  name: 'Codenexsis Technologies',
  shortName: 'Codenexsis',
  url: 'https://codenexsis.com',
  ogImage: 'https://codenexsis.com/og-image.png',
  description:
    'Codenexsis Technologies builds enterprise software, secures critical infrastructure, deploys cloud platforms, and runs the IT networks ambitious companies depend on. Custom development, cybersecurity, IT setup, cloud, and AI — engineered as one stack.',
  shortDescription:
    'Software, security, and the IT backbone behind ambitious companies.',
  tagline: 'The connection between code and outcome.',
  keywords: [
    'software development company UAE',
    'software development Dubai',
    'mobile app development Dubai',
    'custom software development',
    'CRM development',
    'ERP development',
    'mobile app development',
    'SaaS development',
    'cybersecurity services UAE',
    'penetration testing',
    'IT setup and networking',
    'managed IT services',
    'cloud and DevOps',
    'web application development',
    'AI development',
    'enterprise software solutions',
    'Codenexsis',
    'Codenexsis Technologies',
  ],
  authors: [{ name: 'Codenexsis Technologies' }],
  creator: 'Codenexsis Technologies',
  contact: {
    email: 'info@codenexsis.com',
    phone: '+971 50 000 0000',
    address: 'Dubai, United Arab Emirates',
    hours: 'Sun – Thu, 9:00 – 18:00 GST',
  },
  offices: [
    {
      city: 'Dubai',
      country: 'United Arab Emirates',
      flag: '🇦🇪',
      label: 'HQ · Middle East',
      address: 'Dubai, UAE',
      hours: 'Sun – Thu, 9:00 – 18:00 GST',
    },
    {
      city: 'Berlin',
      country: 'Germany',
      flag: '🇩🇪',
      label: 'Europe',
      address: 'Berlin, Germany',
      hours: 'Mon – Fri, 9:00 – 18:00 CET',
    },
    {
      city: 'Islamabad',
      country: 'Pakistan',
      flag: '🇵🇰',
      label: 'Engineering',
      address: 'Islamabad, Pakistan',
      hours: 'Mon – Sat, 9:00 – 18:00 PKT',
    },
  ],
  social: {
    linkedin: 'https://linkedin.com/company/codenexsis',
    twitter: 'https://twitter.com/codenexsis',
    github: 'https://github.com/codenexsis',
    instagram: 'https://instagram.com/codenexsis',
  },
  founded: '2019',
  legalName: 'Codenexsis Technologies LLC',
  pillars: ['Build', 'Secure', 'Scale'],
} as const;

export type SiteConfig = typeof siteConfig;
