import {
  Code2,
  Database,
  Smartphone,
  Globe,
  ShieldCheck,
  Bug,
  Network,
  CloudCog,
  Cloud,
  Cpu,
  BrainCircuit,
  Search,
  TrendingUp,
  Megaphone,
  Target,
  BarChart3,
  Share2,
  PenTool,
  MailCheck,
  MousePointerClick,
  MapPin,
  ShoppingCart,
  Layers,
  type LucideIcon,
} from 'lucide-react';

/** Map an icon name (as stored in the CMS) to its lucide-react component. */
const ICON_MAP: Record<string, LucideIcon> = {
  Code2,
  Database,
  Smartphone,
  Globe,
  ShieldCheck,
  Bug,
  Network,
  CloudCog,
  Cloud,
  Cpu,
  BrainCircuit,
  Search,
  TrendingUp,
  Megaphone,
  Target,
  BarChart3,
  Share2,
  PenTool,
  MailCheck,
  MousePointerClick,
  MapPin,
  ShoppingCart,
};

export const iconByName = (name?: string | null): LucideIcon =>
  (name && ICON_MAP[name]) || Layers;
